################################################################################
#                     PUT SELL STRATEGY CONFIGURATION                        #
################################################################################

# Strategy Configuration
strategy:
  # Strategy name
  name: "PutSellStrat"
  
  # Minimum days to expiration for new positions
  days_to_expiry_min: 60
  
  # Maximum days to expiration for new positions
  days_to_expiry_max: 90
  
  # Whether to sell options (true) or buy options (false)
  is_short: true
  
  # Target delta value for option selection
  # -0.2 = Sell options with approximately 20 delta
  delta_target: -0.2
  
  # Acceptable deviation from target delta when selecting options
  delta_tolerance: 0.01
  
  # Profit target as percentage of max profit (0.65 = exit at 65% of max profit)
  profit_target: 0.65
  
  # Multiple of credit received before triggering stop loss
  # 2.5 = Close position if loss reaches 2.5x the credit received
  stop_loss_threshold: 2.5
  
  # Days to expiration threshold for closing positions
  # 14 = Close positions when they reach 14 days to expiry
  close_days_to_expiry: 14
  
  # Minimum size for new positions (in contracts)
  min_position_size: 1

# Paths Configuration
paths:
  # Input data file containing option chains
  input_file: "C:\\Users\\alexp\\OneDrive\\Gdrive\\Trading\\Data Outputs\\SPY_Combined.csv"
  
  # Directory for storing output logs and results
  output_dir: "C:\\Users\\alexp\\OneDrive\\Gdrive\\Trading\\Data Outputs\\scenario_results"

# Backtest Date Range
dates:
  # Start date for the backtest period (YYYY-MM-DD)
  start_date: "2024-01-02"
  
  # End date for the backtest period (YYYY-MM-DD)
  end_date: "2024-01-10"

# Portfolio Settings
portfolio:
  # Starting capital amount in USD
  initial_capital: 100000
  
  # Maximum leverage allowed for the portfolio
  max_leverage: 12
  
  # Maximum percentage of Net Liquidation Value to deploy
  max_nlv_percent: 0.8
  
  # Maximum position size as percentage of portfolio
  max_position_size_pct: 0.25

# Logging Configuration
logging:
  # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "DEBUG"
  
  # Whether to log to file
  file: true
  
  # Component-specific logging
  components:
    # Margin calculation logging
    margin:
      level: "verbose"
    
    # Portfolio logging
    portfolio:
      level: "verbose"

# Include other configurations
includes:
  # Risk management configuration
  risk_config: "../config/risk/standard_risk.yaml"
  
  # Margin configuration
  margin_config: "../config/margin/span_margin.yaml" 