# Configuration for options trading strategy

# File paths
paths:
  input_file: "C:\\Users\\alexp\\OneDrive\\Gdrive\\Trading\\Data Outputs\\SPY_Combined.csv"
  output_dir: "C:\\Users\\alexp\\OneDrive\\Gdrive\\Trading\\Data Outputs\\scenario_results"
  trades_output_file: "trades.csv"
  verification_output_dir: "C:\\Users\\alexp\\OneDrive\\Gdrive\\Trading\\Data Outputs\\verification_files"

# Date range for backtesting
dates:
  start_date: "2024-01-01"
  end_date: "2024-01-10"

# Portfolio settings
portfolio:
  initial_capital: 100000
  max_leverage: 12
  max_nlv_percent: 1.0
  max_position_size_pct: 0.05  # Reduced from 0.25 to 0.05 (5% per position)
  max_portfolio_delta: 0.50    # 50% of portfolio value as max delta exposure

# Hedging configuration (moved from strategy section)
hedging:
  enabled: true
  mode: "ratio"
  hedge_with_underlying: true  # Use underlying price from option data for hedging
  target_delta_ratio: 0.05     # Reduced from 0.1 to 0.05 (5% of NLV)
  delta_tolerance: 0.1        # Reduced from 0.3 to 0.1 (10% of NLV)
  hedge_symbol: "SPY"
  max_hedge_ratio: 1.5  # Reduced from 3.0 to 1.5

# Risk management settings
risk:
  rolling_window: 21
  target_z: 0
  min_z: -2.0
  min_investment: 0.25
  short_window: 21
  medium_window: 63
  long_window: 252  # Changed to 252 trading days (1 year)
  # Which window to use for risk scaling (short, medium, long)
  risk_scaling_window: "short"

# Strategy parameters
strategy:
  name: "ThetaDecayStrategy"
  # Option selection parameters
  days_to_expiry_min: 60
  days_to_expiry_max: 90
  is_short: true
  delta_target: -0.2
  delta_tolerance: 0.01  # Added tolerance parameter
  profit_target: 0.65
  stop_loss_threshold: 2.5
  close_days_to_expiry: 14
  min_position_size: 1

# Trading parameters
trading:
  normal_spread: 0.60

# Margin management parameters
margin_management:
  # New margin threshold settings
  high_margin_threshold: 0.98   # Increased from 0.90 to 0.98 (98% margin usage)
  target_margin_threshold: 0.95 # Increased from 0.80 to 0.95 (95% margin usage)
  
  # Margin calculation method
  margin_calculation_method: "portfolio"  # Options: "simple" or "portfolio"
  use_portfolio_calculator: true  # Whether to use the portfolio's margin calculator
  
  # Buffer and cooldown settings
  margin_buffer_pct: 0.10
  rebalance_cooldown_days: 3
  
  # Position reduction parameters
  max_position_reduction_pct: 0.25      # Standard max reduction per position (25%)
  losing_position_max_reduction_pct: 0.40 # Higher reduction for losing positions (40%)
  urgent_reduction_pct: 0.50            # Up to 50% in urgent situations

# Reporting parameters
reporting:
  # Enable business logic verification file output
  generate_verification_files: true
  # Enable detailed logging for verification files
  detailed_verification_logging: true
  # Format settings for verification files
  verification_file_format:
    include_trade_manager_logs: true
    include_risk_scaling_logs: true
    include_portfolio_logs: true

# Option Framework Configuration
# This file contains configuration parameters for the entire system

# Paths configuration
paths:
  # Directory for storing output logs and results
  output_dir: "C:/Users/alexp/OneDrive/Gdrive/Trading/Data Outputs/scenario_results"
  # Base directory for loading data
  data_dir: "data"
  # Directory for storing cached data
  cache_dir: "data/cache"

# SPAN Margin Calculator Configuration
# These parameters control how margin requirements are calculated using the SPAN methodology
margin:
  span:
    # Maximum leverage allowed (higher means less margin required)
    # Default: 1.0 (no leverage)
    max_leverage: 12.0
    
    # Initial margin as percentage of notional value
    # Example: 0.1 means 10% of underlying value
    # Range: 0.01 (1%) to 0.2 (20%) is typical
    initial_margin_percentage: 0.1
    
    # Maintenance margin as percentage of notional value (lower than initial margin)
    # Example: 0.07 means 7% of underlying value
    # This is the margin you must maintain to avoid a margin call
    maintenance_margin_percentage: 0.07
    
    # Credit rate applied to hedged positions (0.0 to 1.0)
    # Example: 0.8 means 80% reduction in margin for perfectly hedged positions
    # Higher values result in greater margin reductions for hedged positions
    hedge_credit_rate: 0.8
    
    # Price move percentage for risk scenarios
    # Example: 0.05 means simulate a 5% price move in the underlying
    # Typical range: 0.03 (3%) to 0.15 (15%) depending on asset volatility
    price_move_pct: 0.05
    
    # Volatility shift for risk scenarios (absolute change)
    # Example: 0.3 means simulate a 30% shift in implied volatility
    # Higher values result in more conservative margin requirements
    vol_shift_pct: 0.3
    
    # Volatility multiplier for stress scenarios
    # Example: 1.0 means no additional stress, 1.5 means 50% more risk
    # Higher values result in more conservative margin requirements
    volatility_multiplier: 1.0
    
    # Scaling factor applied to gamma effects to prevent overweighting
    # Example: 0.3 means gamma effects are scaled to 30% of their raw value
    # Typical range: 0.1 to 0.5
    gamma_scaling_factor: 0.3
    
    # Minimum scan risk as percentage of option premium
    # Example: 0.25 means scan risk must be at least 25% of premium
    # Acts as a safety floor for very low calculated risk values
    min_scan_risk_percentage: 0.25
    
    # Maximum ratio of margin to option premium
    # Example: 20.0 means margin cannot exceed 20x the premium
    # Prevents excessively high margin requirements for cheap options
    max_margin_to_premium_ratio: 20.0
    
    # Whether to scale margin lower for out-of-the-money options
    # True: OTM options get reduced margin based on moneyness
    # False: No scaling based on moneyness
    otm_scaling_enabled: true
    
    # Minimum scaling for far out-of-the-money options
    # Example: 0.1 means even very far OTM options still require at least 10% of regular margin
    # Range: 0.05 to 0.5 depending on risk tolerance
    otm_minimum_scaling: 0.1

# Data loading and processing configuration
data:
  # Default chunk size for batch processing
  chunk_size: 1000
  # Use cached data when available
  use_cache: true
  # Cache expiration in days
  cache_expiry_days: 7

# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Format for log messages
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # Log to console
  console: true
  # Log to file
  file: true