# Configuration for options trading strategy

# File paths
paths:
  input_file: "C:\\Users\\alexp\\OneDrive\\Gdrive\\Trading\\Data Outputs\\SPY_Combined.csv"
  output_dir: "C:\\Users\\alexp\\OneDrive\\Gdrive\\Trading\\Data Outputs\\scenario_results"
  trades_output_file: "trades.csv"

# Date range for backtesting
dates:
  start_date: "2024-01-01"
  end_date: "2024-12-31"

# Portfolio settings
portfolio:
  initial_capital: 100000
  max_leverage: 12
  max_nlv_percent: 1.0

# Risk management settings
risk:
  rolling_window: 21
  target_z: 0
  min_z: -2.0
  min_investment: 0.25
  short_window: 21
  medium_window: 63
  long_window: 95
  # Which window to use for risk scaling (short, medium, long)
  risk_scaling_window: "short"

# Strategy parameters
strategy:
  name: "SimpleOptionStrategy"
  # Hedging configuration
  enable_hedging: true
  hedge_mode: "ratio"
  hedge_with_underlying: true  # Use underlying price from option data for hedging
  constant_portfolio_delta: 0.05
  hedge_target_ratio: 1.75
  hedge_symbol: "SPY"
  # Option selection parameters
  days_to_expiry_min: 60
  days_to_expiry_max: 90
  is_short: true
  delta_target: -0.05
  profit_target: 0.65
  stop_loss_threshold: 2.5
  close_days_to_expiry: 14
  delta_tolerance: 1.5
  min_position_size: 1

# Trading parameters
trading:
  normal_spread: 0.60

# Margin management parameters
margin_management:
  margin_buffer_pct: 0.10
  negative_margin_threshold: -0.05
  rebalance_cooldown_days: 3
  forced_rebalance_threshold: -0.10
  # Position reduction parameters
  max_position_reduction_pct: 0.25
  losing_position_max_reduction_pct: 0.40
  urgent_reduction_pct: 0.50